### ISSUE TITLE
Does not work on node 8.x.x

### ISSUE THREAD

**Issue by ristomatti** [biddster/node-red-contrib-ftp-server#5] opened 2018-04-28 15:00 UTC
The node does not appear on the node list. For some reason I am not getting any error on the startup now although I did once get similar error as described on #2.

The issue was closed as node 6 was recommended to be used at the time but currenty the recommended node version is 8.x.x LTS.

**Comment by wb666greene** [comment] 2018-06-06 02:03
Was working for me on Node-RED version: v0.18.7 with Node.js version: v4.8.2 on Raspbian Stretch.

I upgraded Node.js  as recommended by the node-red folks to version: v8.11.2 and it dies with this error:
5 Jun 20:19:34 - [info] Installing module: node-red-contrib-ftp-server, version: 0.2.2
5 Jun 20:19:46 - [info] Installed module: node-red-contrib-ftp-server
5 Jun 20:19:47 - [info] Added node types:
5 Jun 20:19:47 - [info] - node-red-contrib-ftp-server:ftp-server : TypeError: The super constructor to “inherits” must not be null or undefined (line:29)

**Comment by wb666greene** [comment] 2018-06-06 16:47
From the folks at the node-red forum, this may be the root cause of the issue:
https://github.com/nodeftpd/nodeftpd/issues/124

I don't know enough JavaScript to make much sense of it.

**Comment by biddster** [comment] 2018-06-09 21:56
Thanks for the report, I'll try to make some sense of it.

**Comment by biddster** [comment] 2018-06-09 22:49
OK - I've taken a quick look and I can get you going with node 8.x.x whilst I work out what to do for  a more permanent fix.

```
$ cd ~/.node-red/node-modules/node-red-contrib-ftp-server
$ npm install https://github.com/sstur/nodeftpd.git --save
$ vi index.js
```
Now change line 155 from:
```
writeFile: function(fileName, file, callback) {
```
to 
```
writeFile: function(fileName, file, options, callback) {
```

**Comment by wb666greene** [comment] 2018-06-10 22:00
Thanks,  I've made the changes and installed nodejs v8.11.2.  After a reboot all seems to be working so far.  Time will tell if my memory leak goes away or not.  I pass a lot of buffers through the ftp server, dropping most of them in a "filter" function by returning null, the relevant ones get passed on the second filter function output to a Movidius AI Python script via MQTT.  

Memory usage by node-red grows until after 30+ hours it runs out of memory and dies, it gets restarted by systemd a few seconds later and works fine until the cycle repeats,  The node-red folks seemed to think it was the old v4.x nodejs shipped with Raspbian or a leak in the ftpserver node.

I understand 10.x will be an issue as the nodejs ftpd seems to have issues with 10.x

Thanks again for your prompt solution!

Your ftp-server node has been a key piece in adding AI to my video security system and has reduced the false alarm rate to essentially zero.  High priority alerts with near zero false alarm rates will be a game changer in video security monitoring -- I expect it will be near universal in the next generation of Netcams now that chips like the Movidius are available.  I used a Raspberry Pi3B+ to build an add-on to my existing FLIR Lorex DVR system.

**Comment by biddster** [comment] 2018-06-11 21:44
I love what you've done with this node, just brilliant. 

When I've got a little more time, I'll look for a replacement ftp server package. Perhaps there's another that will allow for what we need.

**Comment by det-peralta** [comment] 2018-06-26 22:06
Hello @biddster, thank for the amazing work. Im trying to handle the issue in a node-red docker container. 
I cant edit the index,js to fix the issue. Any other way to add the fix to my node red?
i need the v8, because im use the home assistant connection and its required.

**Comment by biddster** [comment] 2018-06-29 21:22
I'm not sure what's going on with the nodeftpd project. I think I'll have to fork it, fix it and make this node install it from my git fork.

**Comment by biddster** [comment] 2018-07-02 22:00
I've just released 0.3.0 to npm which I hope will sort you out @det-peralta and @wb666greene.

I've forked nodeftpd and install my fork directly from git.

**Comment by det-peralta** [comment] 2018-07-04 10:56
I can confirm this is working in the node-red v8 version, Thank you for the amazing work.

**Comment by biddster** [comment] 2018-07-14 22:23
Closing as confirmed working.

**Closed by biddster** 2018-07-14 22:23 UTC
